#pragma once

#include "stdafx.h"

class I4C3DDIAnalyzeXML;
class I4C3DDIControl;

#define MAX_LOADSTRING			100
#define I4C3D_BUFFER_SIZE		256

#define _STR(x)     #x
#define _STR2(x)    _STR(x)
#define __SLINE__   _STR2(__LINE__)
#define HERE        __FILE__ "("__SLINE__")"

#if DEBUG || _DEBUG
#define DEBUG_PROFILE_MONITOR	DebugProfileMonitor(HERE);
#else
#define DEBUG_PROFILE_MONITOR
#endif

const PCTSTR COMMAND_LIST			= _T("COMMAND_LIST");
const PCTSTR COMMAND_GO_FORWARD		= _T("GO_FORWARD");
const PCTSTR COMMAND_GO_BACKWARD	= _T("GO_BACKWARD");
const PCTSTR COMMAND_GO_UP			= _T("GO_UP");
const PCTSTR COMMAND_GO_DOWN		= _T("GO_DOWN");
const PCTSTR COMMAND_CAMERA_UP		= _T("CAMERA_UP");
const PCTSTR COMMAND_CAMERA_DOWN	= _T("CAMERA_DOWN");
const PCTSTR COMMAND_CAMERA_LEFT	= _T("CAMERA_LEFT");
const PCTSTR COMMAND_CAMERA_RIGHT	= _T("CAMERA_RIGHT");
const PCTSTR COMMAND_SPEED_UP		= _T("SPEED_UP");
const PCTSTR COMMAND_ANIM01_START	= _T("ANIM01_START");
const PCTSTR COMMAND_ANIM02_START	= _T("ANIM02_START");
const PCTSTR COMMAND_ANIM03_START	= _T("ANIM03_START");
const PCTSTR COMMAND_ANIM04_START	= _T("ANIM04_START");

const PCTSTR BUTTON_X				= _T("BUTTON_X");
const PCTSTR BUTTON_A				= _T("BUTTON_A");
const PCTSTR BUTTON_B				= _T("BUTTON_B");
const PCTSTR BUTTON_Y				= _T("BUTTON_Y");
const PCTSTR BUTTON_UP				= _T("BUTTON_UP");
const PCTSTR BUTTON_DOWN			= _T("BUTTON_DOWN");
const PCTSTR BUTTON_LEFT			= _T("BUTTON_LEFT");
const PCTSTR BUTTON_RIGHT			= _T("BUTTON_RIGHT");
const PCTSTR BUTTON_LB				= _T("BUTTON_LB");
const PCTSTR BUTTON_LT				= _T("BUTTON_LT");
const PCTSTR BUTTON_RB				= _T("BUTTON_RB");
const PCTSTR BUTTON_RT				= _T("BUTTON_RT");
const PCTSTR BUTTON_BACK			= _T("BUTTON_BACK");
const PCTSTR BUTTON_START			= _T("BUTTON_START");

const PCTSTR STICK_L_UP				= _T("STICK_L_UP");
const PCTSTR STICK_L_DOWN			= _T("STICK_L_DOWN");
const PCTSTR STICK_L_LEFT			= _T("STICK_L_LEFT");
const PCTSTR STICK_L_RIGHT			= _T("STICK_L_RIGHT");
const PCTSTR STICK_R_UP				= _T("STICK_R_UP");
const PCTSTR STICK_R_DOWN			= _T("STICK_R_DOWN");
const PCTSTR STICK_R_LEFT			= _T("STICK_R_LEFT");
const PCTSTR STICK_R_RIGHT			= _T("STICK_R_RIGHT");

const PCTSTR DELTA					= _T("DELTA");
const PCTSTR CAMERA_MOVE_DELTA		= _T("CAMERA_MOVE_DELTA");
const PCTSTR CAMERA_ANGLE_DELTA		= _T("CAMERA_ANGLE_DELTA");
const PCTSTR CAMERA_PITCH_DELTA		= _T("CAMERA_PITCH_DELTA");
const PCTSTR CAMERA_HEIGHTDELTA		= _T("CAMERA_HEIGHT_DELTA");
const PCTSTR CONTENTS				= _T("CONTENTS");
const PCTSTR ANIMATION01_TITLE		= _T("ANIMATION01_TITLE");
const PCTSTR ANIMATION02_TITLE		= _T("ANIMATION02_TITLE");
const PCTSTR ANIMATION03_TITLE		= _T("ANIMATION03_TITLE");
const PCTSTR ANIMATION04_TITLE		= _T("ANIMATION04_TITLE");

typedef struct I4C3DDICommandSet {
	LPVOID BUTTON_X;
	LPVOID BUTTON_A;
	LPVOID BUTTON_B;
	LPVOID BUTTON_Y;
	LPVOID BUTTON_UP;
	LPVOID BUTTON_DOWN;
	LPVOID BUTTON_LEFT;
	LPVOID BUTTON_RIGHT;
	LPVOID BUTTON_LB;
	LPVOID BUTTON_LT;
	LPVOID BUTTON_RB;
	LPVOID BUTTON_RT;
	LPVOID BUTTON_BACK;
	LPVOID BUTTON_START;

	// 左アナログスティック
	LPVOID STICK_L_UP;
	LPVOID STICK_L_DOWN;
	LPVOID STICK_L_LEFT;
	LPVOID STICK_L_RIGHT;

	// 右アナログスティック
	LPVOID STICK_R_UP;
	LPVOID STICK_R_DOWN;
	LPVOID STICK_R_LEFT;
	LPVOID STICK_R_RIGHT;

	int moveDelta;
	int angleDelta;
	int pitchDelta;
	int heightDelta;

	LPSTR animation01Title;
	LPSTR animation02Title;
	LPSTR animation03Title;
	LPSTR animation04Title;

	int move;
	int angle;
	int pitch;
	int height;
	int speed;
	int x, y, z, p, h, r;

} I4C3DDICommandSet;

typedef struct {
	I4C3DDIAnalyzeXML* pAnalyzer;
	I4C3DDIControl* pController;
	HINSTANCE hInst;
	HWND hWnd;

	SOCKET sender;
	struct sockaddr_in address;

	I4C3DDICommandSet* pCommandSet;
} I4C3DDIContext;